language: node_js
node_js:
  - "8"

services:
  - postgresql

env:
  global:
    - NODE_ENV="test"
    - CAH_DB_USER="cah"
    - CAH_DB_PASSWORD=""
    - CAH_DB_HOST="localhost"
    - CAH_DB_PORT="5432"
    - CAH_DB_ROOT_USER="postgres"
    - CAH_DB_ROOT_PASSWORD=""

before_install:
  - npm install -g nyc codecov
  - cd api_v2

before_script:
  - psql -U postgres -c 'CREATE ROLE cah LOGIN'

install: npm install
script:
  - npm run nyc mocha --exit
  - codecov
