language: node_js
node_js:
  - "8"

services:
  - postgresql

env:
  global:
    - NODE_ENV="test"
    - CAH_DB_USER="cah"
    - CAH_DB_PASSWORD=""
    - CAH_DB_NAME="cah"
    - CAH_DB_HOST="localhost"
    - CAH_DB_PORT="5432"
    - CAH_DB_ROOT_USER="postgres"
    - CAH_DB_ROOT_PASSWORD=""
    - CAH_DATA_PATH="$TRAVIS_BUILD_DIR/data"
    - CAH_MEDIA_PATH="$TRAVIS_BUILD_DIR/media"
    - CAH_API_ADMIN_TOKEN="toquène"

before_install:
  - npm install -g yarn nyc codecov

install:
  - cd "$TRAVIS_BUILD_DIR/api" && yarn
  - cd "$TRAVIS_BUILD_DIR/app" && yarn
  - cd "$TRAVIS_BUILD_DIR/admin" && yarn

before_script:
  - psql -U postgres -c 'CREATE ROLE cah LOGIN'

script:
  - cd "$TRAVIS_BUILD_DIR/api" && yarn lint
  - cd "$TRAVIS_BUILD_DIR/app" && yarn lint
  - cd "$TRAVIS_BUILD_DIR/admin" && yarn lint
  - cd "$TRAVIS_BUILD_DIR/api" && yarn test:coverage
  - nyc report --reporter=text-lcov > coverage.lcov
  - codecov
