#!/bin/sh

source ./.env

source "$VENV_DIR/bin/activate"
source "$NVM_DIR/nvm.sh"

API_URL="http://$CAH_API_IP:$CAH_API_PORT"
API_WS_URL="ws://$CAH_API_IP:$CAH_API_PORT"
WEB_URL="http://$CAH_WEB_IP:$CAH_WEB_PORT"
ADMIN_URL="http://$CAH_ADMIN_IP:$CAH_ADMIN_PORT"

export CAH_DB_NAME
export CAH_DB_USER
export CAH_DB_PASSWORD
export CAH_DB_HOST
export CAH_DB_PORT

export CAH_DB_ROOT_USER
export CAH_DB_ROOT_PASSWORD

export CAH_DATA_PATH
export CAH_MEDIA_PATH
export CAH_AVATARS_PATH

export CAH_API_IP
export CAH_API_PORT

export CAH_WEB_IP
export CAH_WEB_PORT

export CAH_ADMIN_IP
export CAH_ADMIN_PORT

export CAH_API_ADMIN_TOKEN

export CAH_API_ALLOWED_HOSTS="localhost;127.0.0.1;$API_URL;$CAH_API_IP"
export CAH_API_CORS_ORIGIN_WHITELIST="$WEB_URL;$ADMIN_URL"

export REACT_APP_CAH_API_URL=$API_URL
export REACT_APP_CAH_WEBSOCKET_URL=$API_WS_URL
export REACT_APP_CAH_API_ADMIN_TOKEN=$CAH_API_ADMIN_TOKEN

mkdir -p "$CAH_MEDIA_PATH"
mkdir -p "/tmp/avatars"
ln -sf "/tmp/avatars" "$CAH_AVATARS_PATH"
