# Generated by Django 2.0.5 on 2018-07-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=255)),
                ('keep_capitalization', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=255)),
                ('blanks', models.CharField(max_length=255)),
            ],
        ),
    ]
