name: CI

on:
  push:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  types-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: pnpm exec tsc -b

  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: pnpm add -g cspell @cspell/dict-fr-fr
      - run: pnpm exec cspell link add @cspell/dict-fr-fr
      - run: pnpm exec cspell --locale en 'packages/*/src/**/*.{ts,tsx}'

  formatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: pnpm -r --filter='!eslint-config' exec prettier --check src

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: pnpm exec tsc -b
      - run: pnpm -r run lint

  tests:
    runs-on: ubuntu-latest
    container: node:19-slim

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: tests
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: pnpm exec tsc -b
      - run: pnpm -r --workspace-concurrency=1 run test
        env:
          DATABASE_URL: postgres://postgres@postgres:5432/tests
