name: App deployment

on:
  push:
    branches:
      - master

jobs:
  app-deployment:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile
      - run: yarn build
        env:
          NODE_ENV: production
          API_URL: https://cah.nils.cx
          WS_URL: wss://cah.nils.cx
      - run: |
          git add -f dist
          git config --local user.email "deploy@cah.nils.cx"
          git config --local user.name "deploy"
          git commit -m "deploy"
          git push --force ${REMOTE} $(git subtree split --prefix dist):gh-pages
        env:
          REMOTE: https://nilscox:${GITHUB_TOKEN}@github.com/nilscox/cah.git
