name: Build and Deploy

on: [push]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm i -g yarn
    - run: yarn install --frozen-lockfile
      working-directory: ./app
    - name: build
      working-directory: ./app
      run: yarn build:prod
      env:
        API_URL: https://cah.nils.cx
    - name: deploy
      run: |
        git add -f ${DIST}
        git config --local user.email "deploy@cah.nils.cx"
        git config --local user.name "deploy"
        git commit -m "deploy"
        git push --force ${REMOTE} `git subtree split --prefix ${DIST}`:gh-pages
      env:
        DIST: app/dist
        REMOTE: https://nilscox:${GITHUB_TOKEN}@github.com/nilscox/cah.git
